# Generated by Django 4.2.8 on 2023-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenterifcn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esporte', models.CharField(max_length=50)),
                ('dia_horario', models.CharField(max_length=100)),
            ],
        ),
    ]
